runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app

env_variables:
    CLOUDSQL_CONNECTION_NAME: get-that-from-the-console
    CLOUDSQL_USER: scott
    CLOUDSQL_PASSWORD: tiger
    
service: yl-csql-1

libraries:
- name: MySQLdb
  version: "latest"
